2020-11-20 20:54:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-20 21:13:29 ERROR (MainThread) [frontend.js.latest.202010214] https://leaven.duckdns.org:8123/hacsfiles/kiosk-mode/kiosk-mode.js:18:15 Uncaught TypeError: Cannot read property 'config' of undefined
2020-11-20 23:16:24 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 00:08:24 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 00:43:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from n219078024106.netvigator.com (219.78.24.106) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2020.7 (io.robbie.HomeAssistant; build:11; iOS 14.2.0) Mobile/HomeAssistant, like Safari)
2020-11-21 01:25:36 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 19:40:04 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 20:32:01 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 22:37:22 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 22:53:57 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-21 23:38:12 ERROR (MainThread) [custom_components.hacs.repository.integration.fineemb.Lynk-Co] GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
2020-11-21 23:38:12 ERROR (MainThread) [custom_components.hacs.factory] fineemb/Lynk-Co - GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
2020-11-22 00:45:55 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 00:58:09 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 05:10:38 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 06:31:46 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 12:58:12 ERROR (MainThread) [custom_components.hacs.repository.integration.fineemb.Lynk-Co] GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
2020-11-22 12:58:12 ERROR (MainThread) [custom_components.hacs.factory] fineemb/Lynk-Co - GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
2020-11-22 13:00:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 287, in recurring_tasks_installed
    await self.data.async_write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 50, in async_write
    await self.queue.execute()
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 41, in execute
    raise QueueManagerExecutionStillInProgress
queueman.exceptions.QueueManagerExecutionStillInProgress
2020-11-22 19:14:30 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 19:25:14 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 19:46:19 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 20:35:49 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 20:38:14 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 21:13:37 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-22 22:14:52 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.1556259432] Disconnected: Did not receive auth message within 10 seconds
2020-11-23 00:55:59 WARNING (MainThread) [homeassistant.components.automation.turn_on_lights_when_motion_is_detected_in_corridor] 自動化/走廊燈: Already running
2020-11-23 01:36:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1563874544] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-11-23 02:18:11 ERROR (MainThread) [custom_components.hacs.repository.integration.fineemb.Lynk-Co] GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
2020-11-23 02:18:11 ERROR (MainThread) [custom_components.hacs.factory] fineemb/Lynk-Co - GitHub returned 404 for https://api.github.com/repos/fineemb/Lynk-Co
